networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.196.0/24

services:
  ulab-mariadb:
    image: bitnami/mariadb:10.11.8
    container_name: ulab-mariadb
    restart: always
    environment:
      - MARIADB_DATABASE=ulab
      - MARIADB_USER=server
      - MARIADB_PASSWORD=KGzKjZpWBp4R4RSa
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_SKIP_TEST_DB=yes
      - MARIADB_ENABLE_SLOW_QUERY=1
      - MARIADB_LONG_QUERY_TIME=3
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=3000 --max_connections=30000
    #ports:
    #  - 3306:3306
    networks:
      - net
    volumes:
      - ../mariadb/data:/bitnami/mariadb/data
      - ../mariadb/logs:/opt/bitnami/mariadb/logs

  ulab-redis:
    image: 'bitnami/redis:7.2.4'
    container_name: ulab-redis
    restart: always
    networks:
      - net
    environment:
      - REDIS_PASSWORD=nineven

  ulab-server:
    container_name: ulab-server
    restart: always
    image: 'ulab-server'
    build:
      context: system
      dockerfile: Dockerfile
    working_dir: /data/ulab-server
    networks:
      - net
    volumes:
      - ./:/data/ulab-server
    external_links:
      - ulab-mariadb:mariadb
      - ulab-redis:redis
    #extra_hosts:
    # - "mariadb:192.168.196.1"
    sysctls:
      - net.core.somaxconn=4096
    ports:
      - "8896:8896"
    depends_on:
      - ulab-redis
      - ulab-mariadb

