# Generated by Django 5.0.6 on 2024-08-03 10:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NetForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Add Time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('description', models.CharField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('origin_ip', models.GenericIPAddressField(verbose_name='源地址')),
                ('origin_port', models.IntegerField(verbose_name='源端口')),
                ('origin_protocol', models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('RDP', 'RDP'), ('SSH', 'SSH'), ('TELNET', 'TELNET'), ('TCP', 'TCP'), ('UDP', 'UDP')], max_length=20, verbose_name='源协议')),
                ('forward_ip', models.GenericIPAddressField(verbose_name='目标地址')),
                ('forward_port', models.IntegerField(verbose_name='目标端口')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='creator_query', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('dept_belong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='dept_belong_query', to='system.deptinfo', verbose_name='Data Department')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', related_query_name='modifier_query', to=settings.AUTH_USER_MODEL, verbose_name='Modifier')),
            ],
            options={
                'verbose_name': '网络转发',
                'verbose_name_plural': '网络转发',
            },
        ),
    ]
