# Generated by Django 5.0.6 on 2024-08-04 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netforward',
            name='forward_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='目标地址'),
        ),
    ]
