# Generated by Django 5.0.6 on 2024-08-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0002_alter_netforward_forward_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netforward',
            name='forward_port',
            field=models.IntegerField(null=True, verbose_name='目标端口'),
        ),
    ]
