# Generated by Django 5.0.6 on 2024-08-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0004_netforward_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='netforward',
            options={'verbose_name': 'Net Forward', 'verbose_name_plural': 'Net Forward'},
        ),
        migrations.AlterField(
            model_name='netforward',
            name='forward_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='Forward IP'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='forward_port',
            field=models.IntegerField(null=True, verbose_name='Forward Port'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Enable Forward'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='origin_ip',
            field=models.GenericIPAddressField(verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='origin_port',
            field=models.IntegerField(verbose_name='Source Port'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='origin_protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('RDP', 'RDP'), ('SSH', 'SSH'), ('TELNET', 'TELNET'), ('TCP', 'TCP'), ('UDP', 'UDP')], max_length=20, verbose_name='Source Protocol'),
        ),
    ]
