# Generated by Django 5.0.6 on 2024-08-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0005_alter_netforward_options_alter_netforward_forward_ip_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netforward',
            old_name='origin_ip',
            new_name='src_ip',
        ),
        migrations.RenameField(
            model_name='netforward',
            old_name='origin_port',
            new_name='src_port',
        ),
        migrations.RemoveField(
            model_name='netforward',
            name='forward_ip',
        ),
        migrations.RemoveField(
            model_name='netforward',
            name='forward_port',
        ),
        migrations.RemoveField(
            model_name='netforward',
            name='origin_protocol',
        ),
        migrations.AddField(
            model_name='netforward',
            name='dst_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='目标地址'),
        ),
        migrations.AddField(
            model_name='netforward',
            name='dst_port',
            field=models.IntegerField(null=True, verbose_name='目标端口'),
        ),
        migrations.AddField(
            model_name='netforward',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('RDP', 'RDP'), ('SSH', 'SSH'), ('TELNET', 'TELNET'), ('TCP', 'TCP'), ('UDP', 'UDP')], default='', max_length=20, verbose_name='目标协议'),
            preserve_default=False,
        ),
    ]
