# Generated by Django 5.0.6 on 2024-08-08 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0006_rename_origin_ip_netforward_src_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netforward',
            name='dst_ip',
            field=models.GenericIPAddressField(verbose_name='目标地址'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='dst_port',
            field=models.IntegerField(verbose_name='目标端口'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='src_ip',
            field=models.GenericIPAddressField(null=True, verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='netforward',
            name='src_port',
            field=models.IntegerField(null=True, verbose_name='Source Port'),
        ),
    ]
