# Generated by Django 5.0.6 on 2024-08-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nettraversal', '0007_alter_netforward_dst_ip_alter_netforward_dst_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netforward',
            name='protocol',
            field=models.CharField(choices=[('HTTP', 'HTTP'), ('HTTPS', 'HTTPS'), ('RDP', 'RDP'), ('SSH', 'SSH'), ('TELNET', 'TELNET'), ('TCP', 'TCP'), ('UDP', 'UDP')], max_length=20, verbose_name='协议'),
        ),
    ]
